spring.application.name=patient-service
server.port=8089

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

spring.datasource.url=jdbc:postgresql://localhost:5432/patient-service
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC


springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/api-docs

publicKey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnAJSTYmuoneuUgpKfzkeWUo3Z4m9hvOWWp+rc49yIZQas/rOLzPLIc6BMz9g9mcwB6uuiG8KCLe/H3eyMV7V5FBST5anlZB+pt5jWiJwXLkPZrDep11t7xDlNn/jBsxaow2DmoUFWjU0hr1anHFsmM1b7aR2VAV/IE3tDBsfIJenbET2nLXa8I4j/xvG+NGhMwbWrbGD5THbRsoEkrb2Vxzfd/bU/oz5arK6LC759XRhN5fgouj8ZjpnPSmJrim7S2CN+yAsXNhRfe8ru4n1bPyPLdyWKtgQ2aCh7nL2Yn2j+U7k3BmkSeT6p1z72zlLvH77NHbs+LwcvRpjQtKf3QIDAQAB
