rootProject.name = 'doantotnghiep2025'
include 'gateway'
include 'service:auth-service'
include 'service:notification-service'
include 'service:registry-service'
include 'service:user-service'
include 'service:patient-service'
include 'service:medical-record-service'
include 'service:doctor-profile-service'
include 'service:payment-service'
include 'service:laboratory-service'
include 'service:billing-service'
include 'service:prescription-service'
include 'service:pharmacy-service'
include 'service:insurance-service'
include 'service:scheduling-service'
