spring:
  cache:
    type: redis
  data:
    redis:
      host: redis-server
      timeout: 5000
      port: 6379
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000