spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.cloud.gateway.routes[0].id=appointment-service
spring.cloud.gateway.routes[0].uri=lb://appointment-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/appointment-service/**

spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://user-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/user-service/**

spring.cloud.gateway.routes[2].id=inventory-service
spring.cloud.gateway.routes[2].uri=lb://inventory-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/inventory-service/**

spring.cloud.gateway.routes[3].id=insurance-service
spring.cloud.gateway.routes[3].uri=lb://insurance-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/insurance-service/**

spring.cloud.gateway.routes[4].id=patient-service
spring.cloud.gateway.routes[4].uri=lb://patient-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/patient-service/**

spring.cloud.gateway.routes[5].id=doctor-service
spring.cloud.gateway.routes[5].uri=lb://doctor-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/doctor-service/**

spring.cloud.gateway.routes[6].id=labtest-service
spring.cloud.gateway.routes[6].uri=lb://labtest-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/labtest-service/**

spring.cloud.gateway.routes[7].id=payment-service
spring.cloud.gateway.routes[7].uri=lb://payment-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/payment-service/**

spring.cloud.gateway.routes[8].id=invoice-service
spring.cloud.gateway.routes[8].uri=lb://invoice-service
spring.cloud.gateway.routes[8].predicates[0]=Path=/invoice-service/**

spring.cloud.gateway.routes[9].id=prescription-billing-service
spring.cloud.gateway.routes[9].uri=lb://prescription-billing-service
spring.cloud.gateway.routes[9].predicates[0]=Path=/prescription-billing-service/**

spring.cloud.gateway.routes[10].id=clinical-service
spring.cloud.gateway.routes[10].uri=lb://clinical-service
spring.cloud.gateway.routes[10].predicates[0]=Path=/clinical-service/**

spring.cloud.gateway.httpclient.websocket.max-frame-payload-length=65536
spring.cloud.gateway.httpclient.websocket.max-frame-size=65536
spring.cloud.gateway.httpclient.websocket.proxy-ping=true
spring.cloud.gateway.httpclient.websocket.max-idle-time=PT10M
spring.cloud.gateway.httpclient.response-timeout=30000

spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

publicKey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnAJSTYmuoneuUgpKfzkeWUo3Z4m9hvOWWp+rc49yIZQas/rOLzPLIc6BMz9g9mcwB6uuiG8KCLe/H3eyMV7V5FBST5anlZB+pt5jWiJwXLkPZrDep11t7xDlNn/jBsxaow2DmoUFWjU0hr1anHFsmM1b7aR2VAV/IE3tDBsfIJenbET2nLXa8I4j/xvG+NGhMwbWrbGD5THbRsoEkrb2Vxzfd/bU/oz5arK6LC759XRhN5fgouj8ZjpnPSmJrim7S2CN+yAsXNhRfe8ru4n1bPyPLdyWKtgQ2aCh7nL2Yn2j+U7k3BmkSeT6p1z72zlLvH77NHbs+LwcvRpjQtKf3QIDAQAB

spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:3000
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true

spring.cloud.gateway.globalcors.corsConfigurations.[/**].exposedHeaders=Authorization

