spring.application.name=booking-orchestration-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
server.port=8089

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

