syntax = "proto3";
package appointment;
option java_package = "com.example.booking_orchestration_service.grpc.appointment";
option java_multiple_files = true;

service AppointmentService {
  // Activity 1: Giữ chỗ (Lock Redis)
  rpc ReserveSlot (ReserveSlotRequest) returns (ReserveSlotResponse);

  // Activity 3: Ghi DB
  rpc FinalizeBooking (FinalizeBookingRequest) returns (FinalizeBookingResponse);

  // Activity đền bù
  rpc CompensateBooking (CompensateBookingRequest) returns (CompensateBookingResponse);
}

message ReserveSlotRequest {
  string slot_id = 1;
  string patient_id = 2;
  string doctor_id = 3;
}

message ReserveSlotResponse {
  bool success = 1;
}

message FinalizeBookingRequest {
  string slot_id = 1;
  string patient_id = 2;
  string doctor_id = 3;
  string notes = 4;
}
message FinalizeBookingResponse {
  string appointment_id = 1;
}

message CompensateBookingRequest {
  string slot_id = 1;
}
message CompensateBookingResponse {
  bool success = 1;
}