spring.application.name=notification-service

server.port=8094

eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
inventory.service.url=${INVENTORY_SERVICE_URL:http://localhost:8084}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/notification-service}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dathanu123456780913@gmail.com
spring.mail.password=ifxgdeslcthsehhh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
publicKey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnAJSTYmuoneuUgpKfzkeWUo3Z4m9hvOWWp+rc49yIZQas/rOLzPLIc6BMz9g9mcwB6uuiG8KCLe/H3eyMV7V5FBST5anlZB+pt5jWiJwXLkPZrDep11t7xDlNn/jBsxaow2DmoUFWjU0hr1anHFsmM1b7aR2VAV/IE3tDBsfIJenbET2nLXa8I4j/xvG+NGhMwbWrbGD5THbRsoEkrb2Vxzfd/bU/oz5arK6LC759XRhN5fgouj8ZjpnPSmJrim7S2CN+yAsXNhRfe8ru4n1bPyPLdyWKtgQ2aCh7nL2Yn2j+U7k3BmkSeT6p1z72zlLvH77NHbs+LwcvRpjQtKf3QIDAQAB

axon.axonserver.servers=${AXON_AXONSERVER_SERVERS:localhost:8124}
