spring.application.name=payment-service
server.port=8086

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

# Invoice Service Configuration
invoice.service.url=${INVOICE_SERVICE_URL:http://localhost:8091}
inventory.service.url=${INVENTORY_SERVICE_URL:http://localhost:8084}
patient.service.url=${PATIENT_SERVICE_URL:http://localhost:8089}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/payment-service}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false




publicKey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnAJSTYmuoneuUgpKfzkeWUo3Z4m9hvOWWp+rc49yIZQas/rOLzPLIc6BMz9g9mcwB6uuiG8KCLe/H3eyMV7V5FBST5anlZB+pt5jWiJwXLkPZrDep11t7xDlNn/jBsxaow2DmoUFWjU0hr1anHFsmM1b7aR2VAV/IE3tDBsfIJenbET2nLXa8I4j/xvG+NGhMwbWrbGD5THbRsoEkrb2Vxzfd/bU/oz5arK6LC759XRhN5fgouj8ZjpnPSmJrim7S2CN+yAsXNhRfe8ru4n1bPyPLdyWKtgQ2aCh7nL2Yn2j+U7k3BmkSeT6p1z72zlLvH77NHbs+LwcvRpjQtKf3QIDAQAB


# PayOS Configuration
# (Thay th? b?ng key th?t c?a b?n t? dashboard.payos.vn)
payos.client-id=69603884-a518-484e-9990-912b1a0dc267
payos.api-key=b0e2929e-270f-42e3-ae1a-0f248754a9a0
payos.checksum-key=9e4e5600c469624c0c55daaa3d23e3d54e5b3cf105a4cb8f84c56ea5f37f6dfa

# Frontend URLs (D�ng ?? payOS redirect sau khi thanh to�n)
payos.return-url=http://localhost:3000/payment/result
payos.cancel-url=http://localhost:3000/payment/result

# Feign Client Configuration
feign.client.config.default.loggerLevel=full

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true

axon.axonserver.servers=${AXON_AXONSERVER_SERVERS:localhost:8124}


db-scheduler.enabled=true
db-scheduler.table-name=scheduled_tasks
#db-scheduler.threads=10
#db-scheduler.heartbeat-interval=5m
#db-scheduler.missed-heartbeats-limit=6
#db-scheduler.polling-interval=10s
#db-scheduler.shutdown-max-wait=30m

logging.level.org.axonframework.eventhandling=DEBUG

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
